---
# General information
title: Lab Notebook
author: C. Darwin
email: cdarwin@geolsoc.org.uk

# Search path for notebook entries
input_dirs:
  - example/research/*/*

# Location where notebook HTML should be saved to
output_file: example/research/index.html

# File types to include
include_files: ['*.html', '*.py', '*.txt']

# Files to exclude
exclude: ['private']

# Research categories
categories:
  'Finches': ['finch', 'natural-selection']  
  'Barnacles': ['cirripede']  

# Notebook theme
theme: default

