language: python
matrix:
  include:
    - os: linux
      python: 3.3
    - os: linux
      python: 3.4
    - os: linux
      python: 3.5
    - os: osx
      language: generic
before_install:
  - pip install --upgrade pytest
install:
  - pip install .
script: py.test
